"""empty message

Revision ID: 51298677b639
Revises: 6ba9528f0057
Create Date: 2025-01-26 02:42:29.348278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51298677b639'
down_revision = '6ba9528f0057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_planet_pkey')
    )
    op.drop_table('favorite_planets')
    # ### end Alembic commands ###
