"""empty message

Revision ID: 6ba9528f0057
Revises: b907b7e84259
Create Date: 2025-01-26 02:13:44.878342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba9528f0057'
down_revision = 'b907b7e84259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
